# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1fca7a08e6c9d331d71429b7580e17bd0c3f3b12f1ad9bd17336ca45b00ddd720f6c2184c7786c10b25963b7cbf043803e715483d398e51ee35bb127dd183139
  transmission:
    :host: <%= ENV["TRANSMISSION_HOST"] %>
    :port: 9091
    :ssl: true
    :credentials:
      :username: <%= ENV["TRANSMISSION_USERNAME"] %>
      :password: <%= ENV["TRANSMISSION_PASSWORD"] %>

test:
  secret_key_base: e7b110614cc2913b09e2faf150c931a341be1e6164192976a103dce732d68fe6d4019099e83abe655711ac42a8cd29d5271d4b418f705e7dcec29f940f5d5a29

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
